### ISSUE TITLE
Connect the Data Ingestor Microservice with the Plotting Microservice through RabbitMQ

### ISSUE THREAD

**Issue by ParnalPatil** [airavata-courses/CoDist#12]

**Comment by adityarudrawar** [comment]
As asked in the class we have to option to use RabbitMQ or API itself. If we are able to connect the RabbitMQ then we will go through that. Other wise the our API can be the safety net.

**Comment by adityarudrawar** [comment]
This is coded, but wont be uploaded to the development branch de to change in the architecture of the project.

**Comment by ParnalPatil** [comment]
Decided to not pursue this path
